# Generated by cucumber-sinatra. (Tue Mar 22 12:36:22 -0600 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'rubyc.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Rubyc

class RubycWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RubycWorld.new
end
